[tool.poetry]
name = "yamlett"
version = "0.1.0"
description = "Yet Another ML Experiment Tracking Tool"
authors = ["Virgile Landeiro <virgile.landeiro@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pymongo = "^3.11.1"
black = "^20.8b1"
fastcore = "^1.3.9"
pyflakes = "^2.2.0"
loguru = "^0.5.3"
holoviews = "^1.13.5"
panel = "^0.10.2"
numpy = "^1.19.4"
tabulate = "^0.8.7"

[tool.poetry.dev-dependencies]
jupyter = "^1.0.0"
pandas = "^1.1.4"
numpy = "^1.19.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
